definitions:
  bouncer.Response:
    properties:
      allow:
        type: boolean
      callerid:
        type: string
      destination:
        type: string
    type: object
  handler.AuthorizationRequest:
    properties:
      endpoint:
        type: string
      extension:
        type: string
    type: object
  handler.createEndpointRequest:
    properties:
      codecs:
        items:
          type: string
        type: array
      context:
        type: string
      displayName:
        type: string
      extension:
        type: string
      id:
        type: string
      maxContacts:
        type: integer
      password:
        type: string
      realm:
        type: string
      transport:
        type: string
    type: object
  handler.listEndpointEntry:
    properties:
      context:
        type: string
      displayName:
        type: string
      extension:
        type: string
      id:
        type: string
    type: object
  handler.listEndpointsRequest:
    properties:
      endpoints:
        items:
          $ref: '#/definitions/handler.listEndpointEntry'
        type: array
    type: object
host: localhost:8080
info:
  contact: {}
  description: API to perform configuration management on Asterisk servers.
  title: Asterisk Administration API
  version: "1.0"
paths:
  /bouncer:
    post:
      consumes:
      - application/json
      parameters:
      - description: Action to be reviewed
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/handler.AuthorizationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/bouncer.Response'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Determine whether the specified action (call) is allowed or not and
        provide details on how
      tags:
      - bouncer
  /endpoints:
    get:
      parameters:
      - default: 15
        description: Limit the amount of endpoints returned
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.listEndpointsRequest'
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: List existing endpoints.
      tags:
      - endpoints
    post:
      consumes:
      - application/json
      parameters:
      - description: Endpoint's information
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/handler.createEndpointRequest'
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Create a new endpoint.
      tags:
      - endpoints
  /endpoints/{id}:
    delete:
      parameters:
      - description: ID of the endpoint to be deleted
        in: path
        name: id
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Delete an endpoint and its associated resources.
      tags:
      - endpoints
swagger: "2.0"
